name: RaceHolder
version: '${project.version}'
main: io.github.theriverelder.raceholder.RaceHolder
api-version: 1.15
authors: [ TheRiverElder ]
description: A simple plugin to hold and run a race.
commands:
  raceholder:
    description: "用于规划与组织跑道类赛事"
    usage: /raceholder
    aliases: [rh]
    permission: "raceholder.use"
    permission-message: "无权使用比赛规划指令"
